---
abstract: 'client library for fastcgi protocol'
author:
  - 'Tokuhiro Matsuno <tokuhirom @*(#RJKLFHFSDLJF gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FCGI-Client
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Any::Moose: 0.13
  Filter::Util::Call: 0
  IO::Socket::UNIX: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
